# backend/Dockerfile

# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the project code into the container
COPY . /app/

# Expose port 8000
EXPOSE 8000

#Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
